import './global.css';
import { Providers } from 'shared/Featured/provider';
export const metadata = {
  title: 'Home',
  description: 'Generated by create-nx-workspace',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
